import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import AppWalletProvider from "@/components/AppWalletProvider";
import { ReactQueryProvider } from "./react-query-provider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} bg-[#102A43] ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <AppWalletProvider>
            <Header />
            <main className="max-w-6xl mx-auto min-h-screen">
              <div className=" h-24" />
              {children}
              <div className=" h-24" />
            </main>
            <Toaster toastOptions={{}} position="top-center" />
          </AppWalletProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
